steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/proctoride/frontend:$COMMIT_SHA", "./frontend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/proctoride/backend:$COMMIT_SHA", "./backend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/$PROJECT_ID/proctoride/frontend:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/$PROJECT_ID/proctoride/backend:$COMMIT_SHA"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "proctoride-backend",
        "--image",
        "us-central1-docker.pkg.dev/$PROJECT_ID/proctoride/backend:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "proctoride-frontend",
        "--image",
        "us-central1-docker.pkg.dev/$PROJECT_ID/proctoride/frontend:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
